services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: twX
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:

